# NNを関数にまとめたもの

nn.ipynbで手作業でちまちまやっていたNeural Networkの計算処理を関数にまとめたもの。

ここでコスト関数の実装なのも着手していく。

https://www.youtube.com/watch?v=0AX3KSKjyog

In [1]:
import numpy as np
import mnist
import matplotlib.pyplot as plt

In [2]:
data = mnist.load_mnist(flatten = True, one_hot_label=True)

In [3]:
training_idx = 0
test_idx = 1
image_idx = 0
label_idx = 1

In [4]:
inputData = data[training_idx][image_idx]
labelData = data[training_idx][label_idx]

In [7]:
def relu(x):
    return np.maximum(0, x)

In [30]:
# 中間層は2層ある
# それぞれの層は16個のニューロンを持つ
# 単純に積算をするだけ。

def nnv1(inputData):
    weight1 = np.random.rand(len(inputData), 16)
    inputWeight1 = np.dot(inputData, weight1)
    bias1 = np.random.rand(16, )
    layer1 = inputWeight1 + bias1

    weight2 = np.random.rand(len(layer1), 16)
    layer1weight2 = np.dot(layer1, weight2)
    bias2 = np.random.rand(16, )
    layer2 = layer1weight2 + bias2

    weight3 = np.random.rand(len(layer2), 10)
    layer2weight3 = np.dot(layer2, weight3)
    bias3 = np.random.rand(10, )
    layer3 = layer2weight3 + bias3

    output = relu(layer3)
    
    return output

In [31]:
nnv1(inputData[0])

array([3271.22663793, 3836.11808555, 2989.070351  , 3338.80094828,
       4324.95071476, 3589.3197783 , 3760.40531765, 2801.85448029,
       4560.97371316, 3029.6830947 ])

In [32]:
labelData[0]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [33]:
result = nnv1(inputData[0])

In [40]:
pows = np.pow(result - labelData[0], 2)

In [41]:
pows

array([11583113.25588639, 12209586.50249705,  6974289.19720686,
       14639174.21363787, 11742748.65642923, 13151783.81150133,
       11797390.52638505, 13825862.02646185, 12616878.46649833,
        6970319.58325541])

In [43]:
cost = np.sum(pows)

In [46]:
# コスト関数
def cost(result, label):
    return np.sum(np.pow(result - label, 2))

In [45]:
cost(result, labelData[0])

np.float64(115511146.23975936)